---
title: "Air Quality Modelling Assessment"
author: "James David Smith"
output:
  html_document:
    toc: true
    toc_depth: 4
date: "`r format(Sys.time(), '%Y-%m%-%d %H%:%M')`"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "/home/james/", output_file ="graphs.html") })
---

```{r setup, include=FALSE, warning=F, comment=F}
rm(list=ls())

### Loading any missing libraries

library(ggplot2)
library(scales)
library(plotly)
library(rmarkdown)

results <- read.csv('result.csv')

results$datetime <- as.character(results$datetime)
results[grep('/',results$datetime),'datetime'] <- as.character(as.POSIXct(results[grep('/',results$datetime),'datetime'], format='%d/%m/%Y %H:%M'))
results[nchar(results$datetime) == 10,'datetime'] <- paste0(results[nchar(results$datetime) == 10,'datetime'], ' 00:00:00')
results$datetime <- as.POSIXct(results$datetime, '%Y-%m-%d %H:%M:%S')
```

```{r timeline}
pm25 <- ggplot(results, aes(datetime, pm25, colour=sitecode, group=sitecode)) +
  geom_path() +
  theme(legend.position = 'none') +
  scale_x_datetime(breaks = date_breaks("1 hour"))

ggplotly(pm25)
```